### ISSUE TITLE
Steps

### ISSUE THREAD

**Issue by HarshRangwala** [FediSalhi/Deep-Learning-Based-Second-Level-Autonomous-Car#1]
Can you please show the steps on how to run these files?

**Comment by FediSalhi** [comment]
I will add detailed steps as soon as possible. Start by running the test files on your computer (don't forget to change the host and ports) and the Raspberry Pi files. If everything is ok you can then collect your own dataset and train the network. You may need to change some parameters in the Raspberry Pi files such as the ports which your motors are connected to...

**Comment by HarshRangwala** [comment]
Thank you for your reply. I have to submit this project in my college by the end of feb😪. I am done with the hardware part. I have RC car with 2 DC motors connected to a L923D motor driver. However I am stuck in data collection. I can't understand how start with collecting data set. Do I have to first run client_rc_driver.py on my raspberry and then Collect_training_data.py on my computer? just confused. I hope its not too much to ask and you find time to post detailed steps at earliest.

**Comment by FediSalhi** [comment]
To collect dataset you should run client_rc_drive.py and client_stream.py at the same time using two different cmd windows on your Rasp Pi (you won't need to run the third file client_ultrasonic.py for data collection) and collect_training_data on your computer. I don't know if we've got the same hardware but in this project, I've used a 12V DC motor for rear wheels with L923D driver and a Servo motor for the front wheels to steer the car.  You should change the Rasp. Pi files accordingly to your hardware. Good luck and feel free to ask if you need further information.

**Comment by HarshRangwala** [comment]
I just want some clarifications on using ip. So in client_rc_drive.py and client_stream.py I am using laptops ipv4 address : 192.168.0.20 and in collect_training_data.py its my rasp pi's ip. So far right?  I cant get host connected message on my Rasp pi. And after running collect_training_data.py I get this: 
```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Users\xhsh\A3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\xhsh\A3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:/selfdrivingrccar/Computer/collect_training_data.py", line 211, in drive_stream
    s = socketserver.TCPServer((host, port), DriveDataHandler)
  File "C:\Users\xhsh\A3\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\xhsh\A3\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10049] The requested address is not valid in its context
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Users\xhsh\A3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\xhsh\A3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:/selfdrivingrccar/Computer/collect_training_data.py", line 201, in video_stream
    s = socketserver.TCPServer((host, port), VideoStreamHandler)
  File "C:\Users\xhsh\A3\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\xhsh\A3\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10049] The requested address is not valid in its context
```
I have attached the files because I have some mynute changes. It'll be a huge help if you'd take a look at it. Thanks 💯

[client_rc_drive.txt](https://github.com/FediSalhi/Deep-Learning-Based-Second-Level-Autonomous-Car/files/4050773/client_rc_drive.txt)

[collect_training_data.txt](https://github.com/FediSalhi/Deep-Learning-Based-Second-Level-Autonomous-Car/files/4050780/collect_training_data.txt)

No changes in client-stream.py
_________
I am using Anaconda on my laptop.

**Comment by HarshRangwala** [comment]
Hello, You there?

**Comment by FediSalhi** [comment]
Did you open the files on your RaspPi form different windows?? I mean command windows
How are you running the files on your rasp??

**Comment by HarshRangwala** [comment]
yes. I run each files on two different terminals in my raspi

**Comment by HarshRangwala** [comment]
did you look at the files I provided you? are Any possible errors in there?

**Comment by HarshRangwala** [comment]
Am I running the scripts correctly or is there any other way??
